version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0

    steps:
      - checkout
      - run: mvn instsall -DskipTests
      - run: mvn integration-test

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
